[workspace]
resolver = "2"
members = ["crates/jancox-core", "crates/jancox-cli"]

[workspace.package]
version = "3.0.0"
edition = "2021"
rust-version = "1.88"
repository = "https://github.com/wahyu6070/Jancox-tool-android"

[workspace.dependencies]
brotli = "9"
sdat2img = { git = "https://github.com/wahyu6070/sdat2img-rust", tag = "v1.0.0" }
img2sdat = { git = "https://github.com/wahyu6070/img2sdat-rust", tag = "v1.0.0" }
jancox-core = { path = "crates/jancox-core" }

[profile.release]
lto = true
codegen-units = 1
strip = true
