[package]
name = "jancox-core"
description = "Core library of Jancox tool: unpack/repack Android ROMs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
brotli.workspace = true
bzip2.workspace = true
flate2.workspace = true
img2sdat.workspace = true
lzma-rust2.workspace = true
rsa.workspace = true
ruzstd.workspace = true
sdat2img.workspace = true
sha1.workspace = true
sha2.workspace = true
zip.workspace = true
